apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer","app.kubernetes.io/version":"ce-latest-ee-2.21.5","io.portainer.kubernetes.application.stack":"portainer"},"name":"portainer","namespace":"portainer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"}},"spec":{"containers":[{"args":["--tunnel-port=30776"],"image":"portainer/portainer-ce:2.21.5","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/","port":9443,"scheme":"HTTPS"}},"name":"portainer","ports":[{"containerPort":9000,"name":"http","protocol":"TCP"},{"containerPort":9443,"name":"https","protocol":"TCP"},{"containerPort":8000,"name":"tcp-edge","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":9443,"scheme":"HTTPS"}},"resources":{},"volumeMounts":[{"mountPath":"/data","name":"data"}]}],"nodeSelector":{},"serviceAccountName":"portainer-sa-clusteradmin","volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"portainer"}}]}}}}
    creationTimestamp: "2025-02-03T08:51:00Z"
    generation: 6
    labels:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
      app.kubernetes.io/version: ce-latest-ee-2.21.5
      io.portainer.kubernetes.application.stack: portainer
    name: portainer
    namespace: portainer
    resourceVersion: "69434"
    uid: 65b333ff-2225-40b3-bef9-85897ba46a92
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: portainer
        app.kubernetes.io/name: portainer
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-02-03T10:18:47Z"
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: portainer
          app.kubernetes.io/name: portainer
      spec:
        containers:
        - args:
          - --tunnel-port=30776
          image: portainer/portainer-ce:2.21.5
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: portainer
          ports:
          - containerPort: 9000
            name: http
            protocol: TCP
          - containerPort: 9443
            name: https
            protocol: TCP
          - containerPort: 8000
            name: tcp-edge
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: portainer-data
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/hostname: timesheet-workernode-3d5925b611ed
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: portainer-sa-clusteradmin
        serviceAccountName: portainer-sa-clusteradmin
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /portainer/data
            type: Directory
          name: portainer-data
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-02-03T10:18:51Z"
      lastUpdateTime: "2025-02-03T10:18:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-02-03T09:49:26Z"
      lastUpdateTime: "2025-02-03T10:18:51Z"
      message: ReplicaSet "portainer-f798c7b7c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 6
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
