apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer","app.kubernetes.io/version":"ce-latest-ee-2.21.5","io.portainer.kubernetes.application.stack":"portainer"},"name":"portainer","namespace":"portainer"},"spec":{"ports":[{"name":"http","nodePort":30777,"port":9000,"protocol":"TCP","targetPort":9000},{"name":"https","nodePort":30779,"port":9443,"protocol":"TCP","targetPort":9443},{"name":"edge","nodePort":30776,"port":30776,"protocol":"TCP","targetPort":30776}],"selector":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"},"type":"NodePort"}}
    creationTimestamp: "2025-02-03T08:51:00Z"
    labels:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
      app.kubernetes.io/version: ce-latest-ee-2.21.5
      io.portainer.kubernetes.application.stack: portainer
    name: portainer
    namespace: portainer
    resourceVersion: "67952"
    uid: fd69c8f1-6bd1-407c-b0c3-7dd3dfb8140e
  spec:
    clusterIP: 10.98.190.194
    clusterIPs:
    - 10.98.190.194
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: edge
      port: 30776
      protocol: TCP
      targetPort: 30776
    selector:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
