apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsmith-pvc
  namespace: tst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: vultr-block-storage-hdd
