apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsmith-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Must match PVC storageClassName
  hostPath:
    path: "/mnt/data/appsmith"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsmith-pvc
  namespace: tst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Ensures static binding
  volumeName: appsmith-pv  # Bind to specific PV

