apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsmith-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/appsmith"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsmith-pvc
  namespace: tst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


