apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/directus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-pvc
  namespace: tst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

